name: ksoc-guard

on: [ push ]

jobs:
  ksoc-guard:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: KSOC Guard
        uses: ksoclabs/guard-action@v0.0.10
        with:
          policy_dir: /policies
          ignored_paths: /juiceshop-app
